capstone-kelompok-7/backend-disappear

main.go, module/product/domain/models.go, module/product/domain/response.go, module/product/handler/handler.go, module/product/interface.go, module/product/repository/repository.go, module/product/service/service.go, routes/routes.go, utils/database/migrate.go, utils/response/response.go
Done
- Get all products for admin
- Searching Products by name
- Pagination
=> feature:get products

module/auth/domain/request.go, module/auth/handler/handler.go, module/auth/service/service.go, module/auth/service/service_test.go, module/users/service/service.go
improvment feature login-register
- register feature do not require a phone when registering
=> improvment: feature login, register

module/product/domain/models.go, module/product/domain/response.go, module/product/handler/handler.go, module/product/interface.go, module/product/repository/repository.go, module/product/service/service.go, module/review/domain/models.go, module/review/handler/handler.go, module/review/repository/repository.go, module/review/service/service.go, utils/database/migrate.go
=> feature:review

main.go, module/article/domain/models.go, module/article/domain/response.go, module/article/handler/handler.go, module/article/interface.go, module/article/repository/repository.go, module/article/service/service.go, routes/routes.go, utils/database/migrate.go
Feature :
- Get All Article
- Get Article by Title (Search)
- Pagination
=> feature: get article

main.go, module/challenge/domain/models.go, module/challenge/domain/request.go, module/challenge/domain/response.go, module/challenge/handler/handler.go, module/challenge/interface.go, module/challenge/repository/repository.go, module/challenge/service/service.go, routes/routes.go, utils/database/migrate.go
get all challenge + pagination + search
=> feature : challenge

go.mod, module/auth/domain/request.go, module/auth/handler/handler.go, module/auth/interface.go, module/auth/repository/repository.go, module/auth/service/service.go, routes/routes.go
=> feature: resend otp

module/auth/handler/handler.go, module/users/domain/request.go, module/users/handler/handler.go, module/users/interface.go, module/users/repository/respository.go, module/users/service/service.go, routes/routes.go
improvment: feature/changepassword
=> improvment: feature/changepassword

module/feature/auth/handler/handler.go, module/feature/auth/service/service.go, utils/email/email.go, utils/email/template.html
=> improvement:email-template

module/feature/category/handler/handler.go, module/feature/category/service/service.go
improvement error handling on pagination category
=> improvement: clean code category

main.go, module/entities/carousel_models.go, module/feature/carousel/dto/response.go, module/feature/carousel/handler/handler.go, module/feature/carousel/interface.go, module/feature/carousel/repository/repository.go, module/feature/carousel/service/service.go, routes/routes.go, utils/database/migrate.go
added feature get all carousel
=> feature: get all pagination carousel

module/feature/carousel/dto/request.go, module/feature/carousel/handler/handler.go, module/feature/carousel/interface.go, module/feature/carousel/repository/repository.go, module/feature/carousel/service/service.go, routes/routes.go
add feature carousel
- create 
- update
- delete
=> feature:carousel

main.go, module/entities/voucher_models.go, module/feature/voucher/dto/request.go, module/feature/voucher/dto/response.go, module/feature/voucher/handler/handler.go, module/feature/voucher/interface.go, module/feature/voucher/repository/repository.go, module/feature/voucher/service/service.go, routes/routes.go
improvement module voucher
- pagination
- create
- update
- delete
- getbyid
=> improvement:voucher

module/feature/auth/service/service.go, module/feature/users/dto/request.go, module/feature/users/dto/response.go, module/feature/users/handler/handler.go, module/feature/users/interface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, routes/routes.go
new feature for users
- edit profile
- delete account
- get all users pagination
=> feature: user

go.mod, main.go, module/entities/category_models.go, module/entities/product_models.go, module/entities/users_models.go, module/feature/product/dto/request.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, routes/routes.go, utils/response/response.go
What I do : 
- New endpoint : create product
- Improvement : Entity User, Entity Category, Entity Product
- bugfix: fix gorm models deleted_at
=====================================
- if not admin
> ![Screenshot from 2023-11-17 08-47-26](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/336a88e0-c95c-49b2-925c-fb8e02bd1294)
- admin 
> ![Screenshot from 2023-11-17 08-47-50](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/96361e02-a711-497d-ba43-ba3813e74735)
=> feature:create-product

main.go, module/entities/challenge_models.go, module/feature/challenge/dto/request.go, module/feature/challenge/dto/response.go, module/feature/challenge/handler/handler.go, module/feature/challenge/interface.go, module/feature/challenge/repository/repository.go, module/feature/challenge/service/service.go, routes/routes.go
Improvement Challenge create, update, delete, get-by-id
=> improvement : challenge

main.go, module/feature/address/dto/request.go, module/feature/address/dto/response.go, module/feature/address/handler/handler.go, module/feature/address/interface.go, module/feature/address/repository/repository.go, module/feature/address/service/service.go, routes/routes.go
add new module address
- feature get all 
- create address
=> feature: create address

main.go, module/entities/reviews_models.go, module/entities/users_models.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, module/feature/review/dto/request.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/review/interface.go, module/feature/review/repository/repository.go, module/feature/review/service/service.go, module/feature/users/dto/response.go, routes/routes.go, utils/database/migrate.go
added new features in review
- create reviews
error while rating more than 5
=> feature: create review

module/entities/product_models.go, module/feature/product/dto/request.go, module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, routes/routes.go
What i do:
- Get product by ID
- Create Image for product
=> feature:get product id and create product images

main.go, module/entities/product_models.go, module/entities/reviews_models.go, module/feature/product/dto/request.go, module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, module/feature/review/dto/request.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/review/interface.go, module/feature/review/repository/repository.go, module/feature/review/service/service.go, routes/routes.go
Added new feature on review
- create review photo
- update total review on product
- improvement route.go
=> feature: create review photo

module/entities/reviews_models.go, module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/review/interface.go, module/feature/review/repository/repository.go, module/feature/review/service/service.go, routes/routes.go
Module Reviews
- added new feature to count average rating product
- get product reviews on admin
- get detail product reviews on admin
=> feature: count average rating

module/entities/reviews_models.go, module/entities/users_models.go, module/feature/address/dto/request.go, module/feature/address/dto/response.go, module/feature/address/handler/handler.go, module/feature/address/interface.go, module/feature/address/repository/repository.go, module/feature/address/service/service.go, module/feature/category/repository/repository.go, module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/review/interface.go, module/feature/review/repository/repository.go, module/feature/review/service/service.go, routes/routes.go
Module Address
- update address
- delete address
- added is_primary on address models
=> feature: update address

module/feature/product/dto/request.go, module/feature/product/service/service.go
What i do :
- Add the image url payload to the create product endpoint, this endpoint is optional
> ![image](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/486725dd-3e41-4efa-8063-adb894c83a9f)
=> improvement:create product

main.go, module/entities/cart_models.go, module/feature/cart/dto/request.go, module/feature/cart/dto/response.go, module/feature/cart/handler/handler.go, module/feature/cart/interface.go, module/feature/cart/repository/repository.go, module/feature/cart/service/service.go, routes/routes.go, utils/database/migrate.go
added new feature on module cart
- Add prodcut to carts
- Get carts
- Reduce quantity
- Delete carts item
=> feature: cart

module/entities/challenge_models.go, module/feature/challenge/dto/request.go, module/feature/challenge/dto/response.go, module/feature/challenge/handler/handler.go, module/feature/challenge/interface.go, module/feature/challenge/repository/repository.go, module/feature/challenge/service/service.go, routes/routes.go, utils/database/migrate.go
Module Challenge : Join Challenge
Get all submit form + pagination + filter by status
Get by id
User Submit Form follow Challenge
Update status form
=> feature: join-challenge

main.go, module/feature/challenge/interface.go, module/feature/challenge/repository/repository.go, module/feature/challenge/service/service.go, module/feature/users/interface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, routes/routes.go
Module Challenge : Improvement join-challenge
User get exp from challenge
Validation submit form challenge
=> improvement: join-challenge

module/entities/article_models.go, module/entities/carousel_models.go, module/entities/cart_models.go, module/entities/category_models.go, module/entities/challenge_models.go, module/entities/product_models.go, module/entities/reviews_models.go, module/entities/users_models.go, module/entities/voucher_models.go, module/feature/article/service/service.go, module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go
What i do : 
- Improve entities for deleted_at default value is NULL
- Improve response where create, update product and create image for product
- Improve golint in article module
> ![image](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/f113d4c8-6026-4491-be2f-a66f36ae3831)
=> improvement:product and article

module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go
What i do :
- new feature at module product , filter product by category
- improve response for get product by id
> ![image](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/2dba4d2f-9e88-48ce-858b-4eeca7ccd748)
> ![image](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/fb201f96-6482-4c99-9a49-5f3295e23a31)
=> feature:filtering product

module/entities/users_models.go, module/feature/challenge/dto/response.go, module/feature/challenge/handler/handler.go, module/feature/challenge/interface.go, module/feature/challenge/repository/repository.go, module/feature/challenge/service/service.go, module/feature/users/dto/response.go, module/feature/users/interface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, routes/routes.go
Module : Challenge, Users
total follow challenge for users
=> feature: users-total-challenge

.husky/hooks/pre-commit
What i do:
- Husky setup for improve code quality
example if your code bad quality
> ![Screenshot from 2023-11-27 16-58-36](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/f8df9727-0bda-495c-a0eb-da611f511ca2)
The commit will automatically fail when the golinter fails (bad code quality)
=> feature:setup husky

main.go, module/entities/cart_models.go, module/entities/order_models.go, module/entities/voucher_models.go, module/feature/cart/dto/response.go, module/feature/cart/handler/handler.go, module/feature/cart/interface.go, module/feature/cart/repository/repository.go, module/feature/cart/service/service.go, module/feature/order/dto/request.go, module/feature/order/dto/response.go, module/feature/order/handler/handler.go, module/feature/order/interface.go, module/feature/order/repository/repository.go, module/feature/order/service/service.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, module/feature/users/interface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, module/feature/voucher/dto/request.go, module/feature/voucher/dto/response.go, module/feature/voucher/handler/handler.go, module/feature/voucher/interface.go, module/feature/voucher/repository/repository.go, module/feature/voucher/service/service.go, routes/routes.go, utils/database/migrate.go, utils/generator.go
What i do:
Module : order
- create order
- get order byid
- get all order (admin)
- confirm payment (admin)
improve voucher:
- claim voucher
- get voucher users
=> feature: order

module/entities/order_models.go, module/feature/order/dto/response.go, module/feature/order/service/service.go
What i do : 
- fix bug where user create order without voucher
> ![Screenshot from 2023-11-28 19-43-14](https://github.com/capstone-kelompok-7/backend-disappear/assets/93025581/0fe3f58c-5276-4e67-997d-25998df2666a)
=> bugfix:order without voucher

module/feature/address/handler/handler.go, module/feature/article/handler/handler.go, module/feature/auth/handler/handler.go, module/feature/auth/service/service.go, module/feature/carousel/dto/request.go, module/feature/carousel/handler/handler.go, module/feature/cart/dto/response.go, module/feature/cart/handler/handler.go, module/feature/category/handler/handler.go, module/feature/challenge/handler/handler.go, module/feature/order/handler/handler.go, module/feature/product/handler/handler.go, module/feature/product/service/service.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/users/handler/handler.go, module/feature/users/service/service.go, module/feature/voucher/handler/handler.go, module/feature/voucher/repository/repository.go, module/middlewares/auth.go, routes/routes.go, utils/response/response.go
Improvement:
- setup error handling
=> improvement: setup error handling

module/entities/users_models.go, module/feature/address/dto/request.go, module/feature/address/dto/response.go, module/feature/address/handler/handler.go, module/feature/address/service/service.go, module/feature/order/dto/response.go, module/feature/users/dto/response.go, utils/database/mongo.go
improve regarding create address field
=> improvement: create address

module/feature/order/dto/request.go, module/feature/order/handler/handler.go, module/feature/order/interface.go, module/feature/order/repository/repository.go, module/feature/order/service/service.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, routes/routes.go
What I do:
- Order from cart
- Cancel payment (admin)
=> feature: order from  cart

module/feature/challenge/handler/handler.go, module/feature/voucher/handler/handler.go, module/feature/voucher/interface.go, module/feature/voucher/repository/repository.go, module/feature/voucher/service/service.go
Add filter on voucher by category and status
=> feature: filter voucher

main.go, module/feature/dashboard/dto/response.go, module/feature/dashboard/handler/handler.go, module/feature/dashboard/interface.go, module/feature/dashboard/repository/repository.go, module/feature/dashboard/service/service.go, routes/routes.go, utils/response/response.go
What i do :
- Get card for dashboard
=> feature: dashboard

module/feature/challenge/handler/handler.go, module/feature/challenge/repository/repository.go, module/feature/challenge/service/service.go, module/feature/challenge/service/service_test.go
Module Challenge: 
-Improvement Testing coverage 100%, 
-Improvement filter status
=> improvement: testing-challenge

module/entities/reviews_models.go, module/feature/product/dto/response.go, module/feature/product/repository/repository.go
Return user name and avatar user when get product by id
=> improvement: get product by id

module/feature/users/dto/response.go, module/feature/users/handler/handler.go, module/feature/users/interface.go, module/feature/users/mocks/HandlerUserInterface.go, module/feature/users/mocks/RepositoryUserInterface.go, module/feature/users/mocks/ServiceUserInterface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, routes/routes.go
added new feature leaderboard user by exp
=> feature: leaderboard

module/feature/voucher/dto/response.go, module/feature/voucher/handler/handler.go, module/feature/voucher/interface.go, module/feature/voucher/repository/repository.go, module/feature/voucher/service/service.go, routes/routes.go
Module Voucher :  
Get Display Voucher User
=> feature: get-display-vouchers

module/feature/dashboard/dto/response.go, module/feature/dashboard/handler/handler.go, module/feature/dashboard/interface.go, module/feature/dashboard/repository/repository.go, module/feature/dashboard/service/service.go, routes/routes.go
what i do :
- get landing page
- get review on landing page
=> feature: landing page

module/feature/chatbot/handler/handler.go, module/feature/chatbot/interface.go, module/feature/chatbot/service/service.go, routes/routes.go
Improvement : chatbot 
remove parameter name in "/answer"
=> improvement : chatbot

main.go, module/feature/homepage/dto/response.go, module/feature/homepage/handler/handler.go, module/feature/homepage/interface.go, module/feature/homepage/repository/repository.go, module/feature/homepage/service/service.go, routes/routes.go
What i do:
- add get content: category, carousel, best product 
- add get blog post : article and challenge
=> feature: homepage

module/feature/users/dto/response.go, module/feature/users/handler/handler.go, module/feature/users/interface.go, module/feature/users/mocks/HandlerUserInterface.go, module/feature/users/mocks/RepositoryUserInterface.go, module/feature/users/mocks/ServiceUserInterface.go, module/feature/users/repository/respository.go, module/feature/users/service/service.go, routes/routes.go
add feature get user activities (admin)
=> feature: get activities customer

module/feature/dashboard/handler/handler.go, module/feature/dashboard/repository/repository.go, module/feature/dashboard/service/service.go
What i do :
- fixed a bug when the data is equal to 0, the API response will still return the value 0
=> bugfix:fix bug response card dashboard

go.mod, go.sum, main.go, module/feature/auth/service/service.go, utils/caching/redis/redis.go
=> bugfix:fix error pointer redis

module/feature/users/dto/response.go, module/feature/users/handler/handler.go, module/feature/users/interface.go, module/feature/users/mocks/HandlerUserInterface.go, module/feature/users/mocks/ServiceUserInterface.go, module/feature/users/service/service.go, routes/routes.go
=> feature: get user profile

module/feature/product/dto/response.go, module/feature/product/handler/handler.go, module/feature/product/interface.go, module/feature/product/repository/repository.go, module/feature/product/service/service.go, utils/database/mongo.go
i do :
- add filter product by promo
- add total sold at response get product by id
=> improvement: filter product by promo

module/feature/auth/dto/request.go, utils/validate.go
bugfix : register cant use password with space
=> bugfix: validation error while registering

module/feature/order/dto/response.go, module/feature/order/handler/handler.go, module/feature/order/interface.go, module/feature/order/repository/repository.go, module/feature/order/service/service.go, routes/routes.go
[feature : ](feature: get all order users)
=> feature: get all order users

module/feature/order/handler/handler.go, module/feature/order/interface.go, module/feature/order/repository/repository.go, module/feature/order/service/service.go, routes/routes.go
=> feature: accept order

config/config.go, module/entities/product_models.go, module/feature/order/handler/handler.go, module/feature/order/interface.go, module/feature/order/repository/repository.go, module/feature/order/service/service.go, module/feature/product/dto/response.go, module/feature/product/repository/repository.go, module/feature/review/dto/response.go, module/feature/review/handler/handler.go, module/feature/review/interface.go, module/feature/review/repository/repository.go, module/feature/review/service/service.go, routes/routes.go, utils/binderbyte/binderbyte.go
what i do:
- add feature tracking order
- improvement response on review and get product id
=> feature: tracking order

module/feature/homepage/dto/response.go
=> improvment: response homepage

module/entities/users_models.go, module/feature/auth/dto/request.go, module/feature/auth/dto/response.go, module/feature/auth/handler/handler.go, module/feature/auth/interface.go, module/feature/auth/repository/repository.go, module/feature/auth/service/service.go, routes/routes.go
feature: login social
- register using social account
- login using social account
=> feature: login social

module/feature/carousel/handler/handler.go, module/feature/carousel/interface.go, module/feature/category/handler/handler.go, module/feature/category/interface.go, routes/routes.go
get by id carousel
get by id categories
=> feature:getById Categories and Carousel

module/entities/chatbot_models.go, module/feature/cart/dto/response.go, module/feature/cart/repository/repository.go, module/feature/chatbot/dto/request.go, module/feature/chatbot/handler/handler.go, module/feature/chatbot/interface.go, module/feature/chatbot/repository/repository.go, module/feature/chatbot/service/service.go, module/feature/fcm/dto/request.go, routes/routes.go
Improvement Chatbot With Current User
=> improvement: chatbot

module/feature/auth/service/service.go, module/feature/product/service/service_test.go
=> testing:product testing
